# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2110a8969efa7bcf69fbd75231125388832e35d44a33eb420825f67ae9df66afc0f1ad13bccff4ea312499d1f9d4cebf45ec7c4478438a4f5951b38f0b05c2b9

test:
  secret_key_base: 7f1758f2bfcbfad7cc59bfc65fbba4c70dd9843f53a570e47f52b7eb5813c6ca83e7602be6b57132c4424f9f109d7e22e6d5c6374749d98c6726674fdd5029f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
